version: '2.3'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - ./nginx-proxy/nginx-proxy-certs:/etc/nginx/certs:ro
      - ./nginx-proxy/nginx-proxy-vhost:/etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      wp-network:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./nginx-proxy/nginx-proxy-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    networks:
      wp-network:

  wpdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./wordpress-db/wpdb-data:/var/lib/mysql
    networks:
      wp-network:

  wp:
    depends_on:
      - wpdb
    volumes:
      - ./wordpress/wp-data:/var/www/html/wordpress
    ports:
      - "8080:80"
    image: wordpress
    restart: always
    container_name: wp
    environment:
      - WORDPRESS_DB_HOST=wpdb:3306
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
      - VIRTUAL_HOST=www.hear-book.com                      # change this
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=www.hear-book.com                  # change this
      - LETSENCRYPT_EMAIL=nazariazargul@gmail.com           # change this
      - RESOLVE_TO_PROXY_IP=true
    networks:
      wp-network:

networks:
  wp-network:
    driver: bridge

volumes:
  nginx-proxy-certs:
  nginx-proxy-vhost:
  nginx-proxy-certs:
  wpdb-data:
  wp-data:
